spring:
    profiles:
        active:
          - dev
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-ysp-dev
---
spring:
    profiles: test
    application:
        name: microservicecloud-config-ysp-test
# 请保存为UTF-8格式
# 测试git
